Implementation de la feature readlist
Nouuu/Boissibook pull request #62
Opened 2022-05-27 21:06 UTC by SwannHERRERA

Il manque :
- test
- check de validation du user | book

2022-06-06 11:06 UTC, Nouuu commented on src/main/java/org/esgi/boissibook/features/readlist/infra/web/ReadlistCommandController.java
> +        return ResponseEntity.created(URI.create(bookReviewId)).body(new BookReviewIdResponse(bookReviewId));
Regarde la PR de pierre pour la partie URI

2022-06-06 15:41 UTC, SwannHERRERA commented on src/main/java/org/esgi/boissibook/features/readlist/infra/web/ReadlistCommandController.java
> +        return ResponseEntity.created(URI.create(bookReviewId)).body(new BookReviewIdResponse(bookReviewId));
ok j'attends que ça soit merge dans dev

2022-06-07 15:05 UTC, Nouuu requested changes
Globalement je suis d'accord, mais j'ai quand même quelques remarques pour être sûr

2022-06-07 15:05 UTC, Nouuu commented on src/main/java/org/esgi/boissibook/features/readlist/domain/BookReview.java
> +import org.esgi.boissibook.kernel.repository.BookReviewId;
Pas con

2022-06-07 15:05 UTC, Nouuu commented on src/main/java/org/esgi/boissibook/features/readlist/infra/web/ReadlistCommandController.java
> +        return ResponseEntity.created(URI.create(bookReviewId.value())).body(new BookReviewIdResponse(bookReviewId.value()));
A changer au moment de la PR des headers avec haetos

2022-06-07 19:43 UTC, SwannHERRERA commented on src/main/java/org/esgi/boissibook/features/readlist/domain/BookReviewQueryHandler.java
> +
c'est parce qu'ils sont pas encore créé

2022-06-09 06:34 UTC, RemyMach commented on src/main/java/org/esgi/boissibook/features/readlist/infra/web/ReadlistCommandController.java
> +        return ResponseEntity.created(URI.create(bookReviewId.value())).body(new BookReviewIdResponse(bookReviewId.value()));
hateoas tu veux dire ? On compte faire ça parce que ça va demander pas mal de dev et une route register pour avoir les routes au global.

2022-06-09 06:34 UTC, RemyMach commented on src/main/java/org/esgi/boissibook/features/readlist/infra/web/ReadlistCommandController.java
> +        return ResponseEntity.created(URI.create(bookReviewId.value())).body(new BookReviewIdResponse(bookReviewId.value()));
hateoas tu veux dire ? On compte faire ça parce que ça va demander pas mal de dev et une route register pour avoir les routes au global.

2022-06-09 06:35 UTC, RemyMach approved these changes

2022-06-09 10:08 UTC, pooetitu approved these changes

2022-06-09 17:34 UTC, merged